/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMyLabRouteImport } from './routes/app/my-lab'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMyLabIndexRouteImport } from './routes/app/my-lab/index'
import { Route as AppMyLabChecksRouteImport } from './routes/app/my-lab/checks'
import { Route as AppMyLabHealthRouteImport } from './routes/app/my-lab/health'
import { Route as AppMyLabHistoryRouteImport } from './routes/app/my-lab/history'
import { Route as AppMyLabPlanRouteImport } from './routes/app/my-lab/plan'
import { Route as AppMyLabProposalRouteImport } from './routes/app/my-lab/proposal'
import { Route as AppMyLabReportRouteImport } from './routes/app/my-lab/report'
import { Route as AppMyLabSetupRouteImport } from './routes/app/my-lab/setup'
import { Route as AppMyLabTopologyRouteImport } from './routes/app/my-lab/topology'
import { Route as AppProjectIdIndexRouteImport } from './routes/app/project/$id/index'
import { Route as AppProjectIdReportRouteImport } from './routes/app/project/$id/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyLabRoute = AppMyLabRouteImport.update({
  id: '/app/my-lab',
  path: '/app/my-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyLabIndexRoute = AppMyLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabChecksRoute = AppMyLabChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabHealthRoute = AppMyLabHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabHistoryRoute = AppMyLabHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabPlanRoute = AppMyLabPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabProposalRoute = AppMyLabProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabReportRoute = AppMyLabReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabSetupRoute = AppMyLabSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppMyLabTopologyRoute = AppMyLabTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AppMyLabRoute,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/app/project/$id/',
  path: '/app/project/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdReportRoute = AppProjectIdReportRouteImport.update({
  id: '/app/project/$id/report',
  path: '/app/project/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/my-lab': typeof AppMyLabRouteWithChildren
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/my-lab/checks': typeof AppMyLabChecksRoute
  '/app/my-lab/health': typeof AppMyLabHealthRoute
  '/app/my-lab/history': typeof AppMyLabHistoryRoute
  '/app/my-lab/plan': typeof AppMyLabPlanRoute
  '/app/my-lab/proposal': typeof AppMyLabProposalRoute
  '/app/my-lab/report': typeof AppMyLabReportRoute
  '/app/my-lab/setup': typeof AppMyLabSetupRoute
  '/app/my-lab/topology': typeof AppMyLabTopologyRoute
  '/app/my-lab/': typeof AppMyLabIndexRoute
  '/app/project/$id/report': typeof AppProjectIdReportRoute
  '/app/project/$id/': typeof AppProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/my-lab/checks': typeof AppMyLabChecksRoute
  '/app/my-lab/health': typeof AppMyLabHealthRoute
  '/app/my-lab/history': typeof AppMyLabHistoryRoute
  '/app/my-lab/plan': typeof AppMyLabPlanRoute
  '/app/my-lab/proposal': typeof AppMyLabProposalRoute
  '/app/my-lab/report': typeof AppMyLabReportRoute
  '/app/my-lab/setup': typeof AppMyLabSetupRoute
  '/app/my-lab/topology': typeof AppMyLabTopologyRoute
  '/app/my-lab': typeof AppMyLabIndexRoute
  '/app/project/$id/report': typeof AppProjectIdReportRoute
  '/app/project/$id': typeof AppProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/my-lab': typeof AppMyLabRouteWithChildren
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/my-lab/checks': typeof AppMyLabChecksRoute
  '/app/my-lab/health': typeof AppMyLabHealthRoute
  '/app/my-lab/history': typeof AppMyLabHistoryRoute
  '/app/my-lab/plan': typeof AppMyLabPlanRoute
  '/app/my-lab/proposal': typeof AppMyLabProposalRoute
  '/app/my-lab/report': typeof AppMyLabReportRoute
  '/app/my-lab/setup': typeof AppMyLabSetupRoute
  '/app/my-lab/topology': typeof AppMyLabTopologyRoute
  '/app/my-lab/': typeof AppMyLabIndexRoute
  '/app/project/$id/report': typeof AppProjectIdReportRoute
  '/app/project/$id/': typeof AppProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/explore'
    | '/feedback'
    | '/privacy'
    | '/terms'
    | '/app/my-lab'
    | '/app/new'
    | '/app/projects'
    | '/app/settings'
    | '/app/'
    | '/app/my-lab/checks'
    | '/app/my-lab/health'
    | '/app/my-lab/history'
    | '/app/my-lab/plan'
    | '/app/my-lab/proposal'
    | '/app/my-lab/report'
    | '/app/my-lab/setup'
    | '/app/my-lab/topology'
    | '/app/my-lab/'
    | '/app/project/$id/report'
    | '/app/project/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/explore'
    | '/feedback'
    | '/privacy'
    | '/terms'
    | '/app/new'
    | '/app/projects'
    | '/app/settings'
    | '/app'
    | '/app/my-lab/checks'
    | '/app/my-lab/health'
    | '/app/my-lab/history'
    | '/app/my-lab/plan'
    | '/app/my-lab/proposal'
    | '/app/my-lab/report'
    | '/app/my-lab/setup'
    | '/app/my-lab/topology'
    | '/app/my-lab'
    | '/app/project/$id/report'
    | '/app/project/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/disclaimer'
    | '/explore'
    | '/feedback'
    | '/privacy'
    | '/terms'
    | '/app/my-lab'
    | '/app/new'
    | '/app/projects'
    | '/app/settings'
    | '/app/'
    | '/app/my-lab/checks'
    | '/app/my-lab/health'
    | '/app/my-lab/history'
    | '/app/my-lab/plan'
    | '/app/my-lab/proposal'
    | '/app/my-lab/report'
    | '/app/my-lab/setup'
    | '/app/my-lab/topology'
    | '/app/my-lab/'
    | '/app/project/$id/report'
    | '/app/project/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ExploreRoute: typeof ExploreRoute
  FeedbackRoute: typeof FeedbackRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AppMyLabRoute: typeof AppMyLabRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectIdReportRoute: typeof AppProjectIdReportRoute
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-lab': {
      id: '/app/my-lab'
      path: '/app/my-lab'
      fullPath: '/app/my-lab'
      preLoaderRoute: typeof AppMyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/new': {
      id: '/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-lab/': {
      id: '/app/my-lab/'
      path: '/'
      fullPath: '/app/my-lab/'
      preLoaderRoute: typeof AppMyLabIndexRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/checks': {
      id: '/app/my-lab/checks'
      path: '/checks'
      fullPath: '/app/my-lab/checks'
      preLoaderRoute: typeof AppMyLabChecksRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/health': {
      id: '/app/my-lab/health'
      path: '/health'
      fullPath: '/app/my-lab/health'
      preLoaderRoute: typeof AppMyLabHealthRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/history': {
      id: '/app/my-lab/history'
      path: '/history'
      fullPath: '/app/my-lab/history'
      preLoaderRoute: typeof AppMyLabHistoryRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/plan': {
      id: '/app/my-lab/plan'
      path: '/plan'
      fullPath: '/app/my-lab/plan'
      preLoaderRoute: typeof AppMyLabPlanRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/proposal': {
      id: '/app/my-lab/proposal'
      path: '/proposal'
      fullPath: '/app/my-lab/proposal'
      preLoaderRoute: typeof AppMyLabProposalRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/report': {
      id: '/app/my-lab/report'
      path: '/report'
      fullPath: '/app/my-lab/report'
      preLoaderRoute: typeof AppMyLabReportRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/setup': {
      id: '/app/my-lab/setup'
      path: '/setup'
      fullPath: '/app/my-lab/setup'
      preLoaderRoute: typeof AppMyLabSetupRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/my-lab/topology': {
      id: '/app/my-lab/topology'
      path: '/topology'
      fullPath: '/app/my-lab/topology'
      preLoaderRoute: typeof AppMyLabTopologyRouteImport
      parentRoute: typeof AppMyLabRoute
    }
    '/app/project/$id/': {
      id: '/app/project/$id/'
      path: '/app/project/$id'
      fullPath: '/app/project/$id/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project/$id/report': {
      id: '/app/project/$id/report'
      path: '/app/project/$id/report'
      fullPath: '/app/project/$id/report'
      preLoaderRoute: typeof AppProjectIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppMyLabRouteChildren {
  AppMyLabChecksRoute: typeof AppMyLabChecksRoute
  AppMyLabHealthRoute: typeof AppMyLabHealthRoute
  AppMyLabHistoryRoute: typeof AppMyLabHistoryRoute
  AppMyLabPlanRoute: typeof AppMyLabPlanRoute
  AppMyLabProposalRoute: typeof AppMyLabProposalRoute
  AppMyLabReportRoute: typeof AppMyLabReportRoute
  AppMyLabSetupRoute: typeof AppMyLabSetupRoute
  AppMyLabTopologyRoute: typeof AppMyLabTopologyRoute
  AppMyLabIndexRoute: typeof AppMyLabIndexRoute
}

const AppMyLabRouteChildren: AppMyLabRouteChildren = {
  AppMyLabChecksRoute: AppMyLabChecksRoute,
  AppMyLabHealthRoute: AppMyLabHealthRoute,
  AppMyLabHistoryRoute: AppMyLabHistoryRoute,
  AppMyLabPlanRoute: AppMyLabPlanRoute,
  AppMyLabProposalRoute: AppMyLabProposalRoute,
  AppMyLabReportRoute: AppMyLabReportRoute,
  AppMyLabSetupRoute: AppMyLabSetupRoute,
  AppMyLabTopologyRoute: AppMyLabTopologyRoute,
  AppMyLabIndexRoute: AppMyLabIndexRoute,
}

const AppMyLabRouteWithChildren = AppMyLabRoute._addFileChildren(
  AppMyLabRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisclaimerRoute: DisclaimerRoute,
  ExploreRoute: ExploreRoute,
  FeedbackRoute: FeedbackRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AppMyLabRoute: AppMyLabRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectIdReportRoute: AppProjectIdReportRoute,
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
